# Generated by Django 5.0.6 on 2024-07-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='Enter Title', max_length=20)),
                ('Notes', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
