# Generated by Django 5.0.6 on 2024-07-21 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notes',
        ),
    ]
