# Generated by Django 5.0.6 on 2024-07-27 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0005_test1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test1',
            name='User_Name',
        ),
        migrations.AddField(
            model_name='test1',
            name='User_Id',
            field=models.CharField(default='123', max_length=20),
        ),
        migrations.AddField(
            model_name='test1',
            name='test_id',
            field=models.ForeignKey(auto_created=1, default='0', on_delete=django.db.models.deletion.CASCADE, to='Notes.test'),
        ),
    ]
