# Generated by Django 5.0.6 on 2024-07-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0006_remove_test1_user_name_test1_user_id_test1_test_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test1',
            name='test_id',
            field=models.IntegerField(auto_created=1, default=0),
        ),
    ]
