# Generated by Django 5.0.6 on 2024-07-27 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0007_alter_test1_test_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test1',
            name='test_id',
        ),
    ]
