# Generated by Django 5.0.6 on 2024-07-28 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0008_remove_test1_test_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test1',
            name='User_Id',
        ),
        migrations.RemoveField(
            model_name='test1',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='test1',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='test1',
            name='password',
        ),
        migrations.AddField(
            model_name='test1',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
