# Generated by Django 5.0.6 on 2024-07-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0010_rename_user_id_test1_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='U_Id',
            field=models.IntegerField(default=0),
        ),
    ]
