# Generated by Django 5.0.6 on 2024-07-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0011_test_u_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='U_Id',
            field=models.TextField(default=0),
        ),
    ]
