# Generated by Django 5.0.6 on 2024-07-31 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0013_remove_test_u_id_test_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='User_Name',
        ),
        migrations.AddField(
            model_name='test',
            name='U_Id',
            field=models.IntegerField(default=0),
        ),
    ]
