# Generated by Django 5.0.6 on 2024-07-31 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0014_remove_test_user_name_test_u_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='U_Id',
        ),
        migrations.AddField(
            model_name='test',
            name='User_Name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
