# Generated by Django 5.0.6 on 2024-08-02 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0016_test12'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test12',
        ),
    ]
