# Generated by Django 5.0.6 on 2024-08-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0017_delete_test12'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='User_Name',
        ),
        migrations.AddField(
            model_name='test',
            name='U_Id',
            field=models.IntegerField(default=0),
        ),
    ]
